name = "fener"

[variables]
version = "0.0.1"

[task.build]
description = "Build the project."
command = "go build ."
depends = [
    "generate",
    "format"
]


[task.test]
command = "go test ./... -test.fullpath -timeout 1000ms"
depends = [
    "format",
    "build"
]

[task.format]
command = "go fmt ./..."

[task.run]
command = "./fener repl"
depends = ["build"]

[task.generate]
command = "go generate ./..."
description = "Generate stringer code."
